config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :surveys, only: [:index] do
    resources :attempts, except: [:edit, :update, :destroy]

  end

  namespace :admin do
    resources :surveys do
      resources :attempts
    end
    get '/' , to: 'surveys#index'
  end

  root 'surveys#index'
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  # associations
  has_many :attempts, dependent: :destroy
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true, reject_if: lambda { |question| question[:text].blank? }

  # scopes
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  # validations
  #validates :attempts_number, numericality: { only_integer: true, greater_than: -1 }
  validate :at_least_one_question
  # validate :at_least_one_option_correct
  validates :description, :name, presence: true, allow_blank: false
  validates :questions, nested_attributes_uniqueness: {field: :text}

  def to_s
    name
  end

  def correct_options # returns all the correct options for current surveys
    return self.questions.map(&:correct_options).flatten
  end


  def incorrect_options # returns all the incorrect options for current surveys
    return self.questions.map(&:incorrect_options).flatten
  end


  # def self.import_from_csv(file)
  #   file = File.read(file.path)
  # end # end self.import(file)



  require 'json'
  def self.import_from_json#(file)

    file = File.read("#{Rails.root}/doc/survey_2.json")
    data_hash = JSON.parse(file)


    new_record = Survey.new
    #new_record.id = data_hash['id']
    new_record.name = data_hash['name']
    new_record.description = data_hash['description']
    new_record.attempts_number = data_hash['attempts_number']
    new_record.active = data_hash['active']

    data_hash['questions'].each do |question|
      new_question =  new_record.questions.new
      #new_question.id              = question['id']
      new_question.survey_id       = question['survey_id']
      new_question.text            = question['text']
      new_question.multiple_choice = question['multiple_choice']
      new_question.weight          = question['weight']
      question['options'].each do |option|
        new_option =  new_question.options.new
        #new_option.id          = option['id']
        new_option.question_id = option['question_id']
        new_option.text        = option['text']
        new_option.correct     = option['correct']
      end
    end

    new_record.save
  end

  private

  def at_least_one_question
    errors.add(:base, :must_have_at_least_one_question, {text: self.text}) if questions.size < 1
  end

  # def available_for_participant?(participant)
  #   current_number_of_attempts = self.attempts.for_participant(participant).size
  #   upper_bound = self.attempts_number
  #   return !((current_number_of_attempts >= upper_bound) && (upper_bound != 0))
  # end
end

# == Schema Information
#
# Table name: surveys
#
#  id              :integer          not null, primary key
#  name            :string
#  description     :text
#  attempts_number :integer
#  active          :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController  < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  respond_to :html
  responders :flash

  def index
    @surveys = Survey.all
  end

  def show
  end

  def new
    @survey = Survey.new
    @survey.questions.build
  end

  def edit
  end

  def create
    @survey = Survey.create(survey_params)
    respond_with(:admin, @survey)
  end

  def update
    @survey.update(survey_params)
    respond_with(:admin, @survey)
  end

  def destroy
    @survey.destroy
    respond_with @survey, location: admin_surveys_path
  end

  private
  def set_survey
    @survey = Survey.find(params[:id])
  end


  def survey_params
    params.require(:survey)
        .permit(
            :id,
            :name, :description, :attempts_number, :active,
            # has_many :questions (Nested Attributes)
            questions_attributes: [
                :survey_id,
                :id,
                :text,
                :explanation,
                :_destroy,
                :multiple_choice,
                :peso,
                :weight,
                # :has_many :options (Nested Attributes)
                options_attributes: [
                    :question_id,
                    :id,
                    :text,
                    :_destroy,
                    :correct
                ]
            ]
        )
  end
end


# Table name: questions
#
#  id              :integer          not null, primary key
#  survey_id       :integer
#  text            :string
#  multiple_choice :boolean


# Table name: options
#
#  id          :integer          not null, primary key
#  question_id :integer
#  weight      :integer
#  text        :string
#  correct     :boolean

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    @surveys = Survey.all
  end

end


# Table name: questions
#
#  id              :integer          not null, primary key
#  survey_id       :integer
#  text            :string
#  multiple_choice :boolean


# Table name: options
#
#  id          :integer          not null, primary key
#  question_id :integer
#  weight      :integer
#  text        :string
#  correct     :boolean

app/helpers/surveys_helper.rb
module SurveysHelper

  def link_to_add_fields(name, f, association, options = {})
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + '_fields', f: builder)
    end
    link_to(name, '#', class: "add_fields  #{options[:class]}", data: {id: id, fields: fields.gsub("\n", "")})
  end

end

app/views/admin/surveys/_form.html.erb
<%= form_for([:admin, @survey], html: {class: 'survey-form'}) do |f| %>
    <%= render 'shared/error_messages', object: @survey if @survey.errors.any? %>

    <div class='field'>
      <div class='row'>
        <div class='form-group col-sm-4'>
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class='form-group col-sm-4'>
          <%= f.label :attempts_number, 'Maximum number of attempts (0 is infinite)' %>
          <%= f.number_field :attempts_number, min: 0, class: 'form-control' %>
        </div>
        <div class='form-group col-sm-4'>
          <%= f.label :active %>
          <%= f.select :active, ['true', 'false'], {}, class: 'form-control' %>
        </div>
      </div>

      <div class='row'>
        <div class='form-group col-sm-12'>
          <%= f.label :description %>
          <%= f.text_area :description, size: '100x5', class: 'form-control', style: 'max-width: 100%;' %>
        </div>
      </div>

      <div class='row question'>
        <%= f.fields_for :questions do |builder| %>
            <%= render 'question_fields', f: builder %>
        <% end %>

      <%= link_to_add_fields '', f, :questions, class: 'glyphicon glyphicon-plus btn btn-primary add_fields_link pull-right add' %>
      </div>
    </div>

    <div class="actions pull-right align-actions">
      <%= link_to t('back'), admin_surveys_path, class: 'btn btn-default' %>
      <%= f.submit class: 'btn btn-primary', id: 'submit_survey', data: {disable_with: 'processing'} %>
    </div>

<% end -%>
<%= content_for :script do %>
    <script type='text/javascript'>
        $("form").submit(function () {
            $('textarea.escaped').each(
                    function (index) {
                        var input = $(this);

                        var escaped_content = input.val()
                                .replace(/"/g, '&quot;')
                                .replace('”', '&quot;')
                                .replace(/'/g, '&#39;')
                                .replace(/</g, '&lt;')
                                .replace(/>/g, '&gt;');

                        input.val(escaped_content);

                    }
            );
        });


        $(document).ready(function () {
            turn_textareas_autogrow();
            setTimeout(function () {//page going to top
                $('.add_fields:last').focus();
            }, 200);

            $('.add').click(function () {
                $('.bs-callout-primary.fields:visible').each(function () {
                    correct_options = $(this).find('.correct_options input[type="checkbox"]:checked').length;//get number of options correct
                    if (correct_options == 0) {
                        $(".add").attr({
                            'data-confirm': "Questions must have at least one option correct.",
                            'data-ok': "Ok",
                            'data-cancel': 'Cancelar'
                        });
                        $(this).addClass("bs-callout bs-callout-danger");
                        $(this).attr("tabindex",-1).focus(); //focus on div with question without option correct
                    }
                    else{
                        $(this).addClass("bs-callout bs-callout-primary");
                    }
                });
            });
        });

        function turn_textareas_autogrow() {

            $('textarea.autogrow').each(function () {//fix grow onload
                autogrower($(this));
            });

            $('textarea.autogrow').bind('input keyup change cut paste', function () {
                autogrower($(this));
            });
        }

        function autogrower(element) {
            $(element).css("height", 'auto');
            $(element).css("height", element[0].scrollHeight + 3 + 'px');
        }
    </script>
<% end %>



<!--http://localhost:3000/surveys/3/attempts/18-->

<!--//alert('Type: ' + input.attr('type') + 'Name: ' + input.attr('name') + 'Value: ' + input.val());-->
<!--var escaped_content = input.val()-->
<!--.replace(/&/g, '&amp;')-->
<!--.replace(/>/g, '&gt;')-->
<!--.replace(/</g, '&lt;')-->
<!--.replace(/"/g, '&quot;')-->
<!--.replace(/'/g, '&apos;');-->

app/views/admin/surveys/_option_fields.html.erb
<li class="row fields">
  <div class="form-group col-xs-9">
    <%#= f.cktext_area :text, placeholder: 'answer', rows: '3', class: 'form-control escaped' %>
    <%= f.text_area :text, placeholder: 'answer', rows: '3', class: 'form-control escaped autogrow' %>
  </div>

  <div class="checkbox col-xs-2 col-sm-2 correct_options">
    <%= f.label :correct do %>
        <%= check_box_for f, :correct %>
    <% end %>
  </div>

  <div class="col-xs-1">
    <%= f.hidden_field :_destroy %>
    <%= link_to '', '#', class: 'glyphicon glyphicon-remove btn  btn-danger remove_fields' %>
  </div>

</li>

app/views/admin/surveys/_question_fields.html.erb
<div class="bs-callout bs-callout-primary fields">

  <fieldset>
    <legend>Question <%= f.options[:child_index] + 1 %></legend>

    <div class="form-group">
      <%= f.label :text %>
      <%= f.text_area :text, placeholder: 'question', rows: '6', class: 'form-control escaped' %>
    </div>

    <div class="form-group">
      <%= f.label :weight %>
      <%= f.text_field :weight, class: 'form-control-short' %>

      <%= f.label :multiple_choice do %>
          <%= check_box_for f, :multiple_choice %>
      <% end %>
    </div>

    <fieldset>
      <legend>Options </legend>
      <ol class="lower-alpha convert-code-options">
        <%= f.fields_for :options do |builder| %>
            <%= render 'option_fields', f: builder %>
        <% end -%>
        <%= link_to_add_fields '', f, :options, class: 'textareautosize glyphicon glyphicon-plus btn btn-info add_fields_link pull-right ' %>
      </ol>
    </fieldset>

    <div class="form-group">
      <%= f.label :explanation %>
      <%= f.text_area :explanation, placeholder: 'question', rows: '3', class: 'form-control' %>
    </div>

    <%= f.hidden_field :_destroy %>
    <%= link_to '', '#', class: 'glyphicon glyphicon-remove btn  btn-danger remove_fields' %>
  </fieldset>
</div>

app/views/admin/surveys/edit.html.erb
<h2>Editing Survey</h2>

<%= render 'form' %>

app/views/admin/surveys/index.html.erb
<h2>Surveys</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Attempts number</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= link_to(survey.name, [:admin, survey]) %></td>
        <td><%= survey.description %></td>
        <td><%= survey.attempts_number %></td>
        <td><%= survey.active %></td>
        <td><%= link_to '', new_survey_attempt_path(survey), class: 'glyphicon glyphicon-play btn-xs btn-success', title: "Start"%></td>
        <td><%= link_to '', edit_admin_survey_path(survey), class: 'glyphicon glyphicon-pencil btn-xs btn-primary', title: "Editar" %></td>
        <td><%= link_to '', admin_survey_path(survey), method: :delete, data: {confirm:'Are you sure?', ok:  'ok' , cancel:  'cancel'}, class: 'glyphicon glyphicon-remove btn-xs btn-danger', title: "Excluir" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="actions pull-right">
  <%= link_to t('back'), admin_surveys_path, class: 'btn btn-default' %>
  <%= link_to 'New Survey', new_admin_survey_path, class: 'btn btn-primary' %>
</div>

app/views/admin/surveys/new.html.erb
<h2>New Survey</h2>

<%= render 'form' %>

app/views/admin/surveys/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @survey.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @survey.description %>
</p>

<p>
  <strong>Attempts number:</strong>
  <%= @survey.attempts_number %>
</p>

<p>
  <strong>Questions:</strong>
  <%= @survey.questions.try(:lenght) %>
</p>

<p>
  <strong>Active:</strong>
  <%= @survey.active %>
</p>

<ul class="questions ">
<% @survey.questions.each.with_index(1) do |question, index| %>
    <li>
      <h4>Question <%= index %></pre></h4>
      <span class="convert-code-title"><%= question.text.html_safe %></span>
      <p><strong>multiple choice:</strong> <%= question.multiple_choice %>  <strong>weight: <%= question.weight %></strong></p>

      <ol class="options lower-alpha convert-code-options">
        <% question.options.each do |option| %>
            <li class="<%= option.correct? ? 'correct-answer' : 'wrong-answer'%>">
              <label><%= option.text.html_safe %></label>
            </li>
        <% end %>
      </ol>

      <strong>Explanation:</strong> <br /><%= question.explanation %>
    </li><hr />
<% end %>
</ul>

<div class="actions pull-right">
  <%= link_to t('all'), admin_surveys_path, class: 'btn btn-default' %>
  <%= link_to t('edit'), edit_admin_survey_path(@survey), class: 'btn btn-primary' %>
</div>


<%= content_for :script do %>
    <%= render 'shared/javascript_highlight_function' %>
<% end %>