config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :surveys, only: [:index] do
    resources :attempts, except: [:edit, :update, :destroy]

  end

  namespace :admin do
    resources :surveys do
      resources :attempts
    end
    get '/' , to: 'surveys#index'
  end

  root 'surveys#index'
end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
  # associations
  belongs_to :participant, polymorphic: true
  belongs_to :survey
  has_many :questions, through: :survey
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers ,
                                reject_if: ->(answers) { answers[:option_id].blank? }

  # validations
  # validates :participant_id, :participant_type, presence: true

  #scopes
  #scope :answered_questions, ->(attempt) { Answer.where(attempt: attempt) }

  def score
    correct_answered_questions.map(&:weight).inject(&:+)
  end


  def answered_questions
    answers.map(&:question).uniq
  end

  def answered_options(question)
    answers.includes(:option).where(options: {question_id: question.id}).pluck(:option_id)
  end

  def correct_answered_questions
    questions = answers.map(&:question)
    corrects = []
    questions.each do |question|
      corrects.push(question) if correct_answered_options?(question)
    end
    corrects.uniq
  end


  def correct_answered_options?(question)
    answered_options = self.answers.includes(:option).where(options: {question_id: question.id}).pluck(:option_id).compact
    correct_options = question.correct_options.pluck(:id)
    answered_options.uniq.sort == correct_options.uniq.sort
  end

end


# == Schema Information
#
# Table name: attempts
#
#  id               :integer          not null, primary key
#  participant_id   :integer
#  participant_type :string
#  survey_id        :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_attempts_on_participant_type_and_participant_id  (participant_type,participant_id)
#  index_attempts_on_survey_id                            (survey_id)
#



# survey = Survey.first
# attempt = survey.attempt.new
# attempt.participant = User.firt
#
# attempt.answers.new({})

app/controllers/admin/attempts_controller.rb
class Admin::AttemptsController < ApplicationController
  before_action :find_survey
  before_action :set_attempt, only: [:show, :edit, :update, :destroy]

  respond_to :html
  responders :flash

  def index
    @attempts = Attempt.all
  end

  def show
  end

  def new
    @attempt = @survey.attempts.new
  end

  def edit
  end

  def create
    @attempt = @survey.attempts.create(attempt_params)
    respond_with(:admin, @survey, @attempt)
  end

  def update
    @attempt.update(attempt_params)
    respond_with(:admin, @survey, @attempt)
  end

  def destroy
    @attempt.destroy
    respond_with @attempt, location: survey_attempts_path(:admin, @survey)
  end

  private
  def set_attempt
    @attempt = Attempt.find(params[:id])
  end

  def find_survey
    @survey = Survey.find(params[:survey_id])
  end

  def attempt_params
    params.require(:attempt).permit(:participant_id, :participant_type, :survey_id, :winner, :score, answers_attributes: [:id, :attempt_id, :option_id, :question_id])
  end
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  before_action :find_survey
  before_action :set_attempt, only: [:show]

  respond_to :html
  responders :flash

  def index
    @attempts = Attempt.all
  end

  def show
  end

  def new
    @attempt = @survey.attempts.new
  end

  def create
    @attempt = @survey.attempts.create(attempt_params)
    respond_with(@survey, @attempt)
  end

  private
  def set_attempt
    @attempt = Attempt.find(params[:id])
  end

  def find_survey
    @survey = Survey.find(params[:survey_id])
  end

  def attempt_params
    params.require(:attempt).permit(:participant_id, :participant_type, :survey_id, :winner, :score, answers_attributes: [:id, :attempt_id, :option_id, :question_id])
  end
end

app/views/admin/attempts/_form.html.erb
<%#= form_for([@survey, @attempt]) do |f|
    <%= form_for([:admin, @user], method: :put) do |f| %>
<%= form_for([:admin, @survey, @attempt]) do |f| %>
    <%= render 'shared/error_messages', object: @attempt if @attempt.errors.any? %>
    <%= hidden_field_tag "attempt[participant_id]", 1 %>
    <%= hidden_field_tag "attempt[participant_type]", 'User' %>

    <h2 class="survey"><%= @survey.name %></h2>

    <ol class="questions">
      <% answer_idx = 0 %>
      <% @survey.questions.each do |question| %>
          <li>
            <h4 class="question"><%= question.text.html_safe %></h4>
            <ol class="options lower-alpha convert-code-options">
              <% question.options.each do |option| %>
                  <li>
                    <label>
                      <% @attempt.answers.build %>
                      <% answer_idx += 1 %>
                      <%= check_box_tag "attempt[answers_attributes][#{answer_idx}][option_id]", option.id, f.object.answers.include?(option) %>
                      <%= option.text.html_safe %>
                    </label>
                  </li>
              <% end %>
            </ol>
            <hr/>
          </li>
      <% end %>
    </ol>
    <div class="actions pull-right">
      <%= link_to t('back'), admin_survey_attempts_path(@survey), class: 'btn btn-default' %>
      <%= f.submit class: 'btn btn-primary', id: 'submit_attempt', data: {disable_with: 'processing'} %>
    </div>
<% end -%>

<%= content_for :script do %>
    <%= render 'shared/javascript_highlight_function' %>
<% end %>

app/views/admin/attempts/edit.html.erb
<h2>Editing Attempt</h2>

<%= render 'form' %>

app/views/admin/attempts/index.html.erb
<h2>Attempts</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <!--<th>Participant</th>-->
      <th>Survey</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attempts.each do |attempt| %>
      <tr>
        <!--<td><%#= attempt.participant %></td>-->
        <td><%= attempt.survey %></td>
        <td><%= link_to 'Show', [:admin, @survey, attempt] %></td>
        <td><%= link_to 'Edit', edit_admin_survey_attempt_path(@survey, attempt) %></td>
        <td><%= link_to 'Destroy', [:admin, @survey, attempt], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="actions pull-right">
  <%= link_to t('back'),  admin_survey_attempts_path, class: 'btn btn-default' %>
  <%= link_to 'New Attempt', new_admin_survey_attempt_path, class: 'btn btn-primary' %>
</div>

app/views/admin/attempts/new.html.erb
<h2>New Attempt</h2>

<%= render 'form' %>

app/views/admin/attempts/show.html.erb
<!--<p>-->
<!--<strong>Participant:</strong>-->
<!--<%#= @attempt.participant %>-->
<!--</p>-->
<h2>Result</h2>
<h3> <%= @attempt.survey %> </h3>

<ol class="questions">
  <% @attempt.answered_questions.each do |question| %>
      <li>
        <h3><%= question.text %></h3>
        <p>
          <strong>multiple choice:</strong> <%= question.multiple_choice %>
          <strong>weight: 5 </strong>
          <strong>correct?:</strong> <%= @attempt.correct_answered_options?(question) %>
        </p>
        <ul class="options">
          <% question.options.each do |option| %>
              <% my_options = @attempt.answers.includes(:option).where(options: {question_id: question.id}).pluck(:option_id).compact %>
              <li>
                <%= check_box_tag 'tos', 'yes', my_options.include?(option.id), class: 'options' %>
                <label class="<%= option.correct? ? 'correct-answer' : 'wrong-answer' %>"> <%= option.text %></label>
              </li>
          <% end %>
        </ul>
        <strong>Explanation:</strong> <br /><%= question.explanation %>
      </li>
      <hr/>
  <% end %>
</ol>

<div class="actions pull-right">
  <%= link_to t('all'), admin_survey_attempts_path(@survey), class: 'btn btn-default' %>
  <%= link_to t('edit'), edit_admin_survey_attempt_path(@survey, @attempt), class: 'btn btn-primary' %>
</div>