config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :surveys, only: [:index] do
    resources :attempts, except: [:edit, :update, :destroy]

  end

  namespace :admin do
    resources :surveys do
      resources :attempts
    end
    get '/' , to: 'surveys#index'
  end

  root 'surveys#index'
end

app/views/shared/_error_messages.erb
<% if object.errors.any? %>
    <div class="alert alert-danger fade in">
      <h4><%= t('activerecord.errors.template.body')%></h4>
      <button class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_flash_messages.erb
<% flash.each do |type, message| %>
    <% unless flash[type].blank? %>
        <div class="alert <%= flash_class(type) %> fade in">
          <button class="close" data-dismiss="alert" aria-hidden="true">×</button>
           <%= raw(message) %>
        </div>
    <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Copyright © 2016  <%= link_to 'Exam Tests', '#', target: '_blank' %>, released under the MIT license.</p>
  </div>
</footer>

app/views/shared/_javascript_cdn_includes.erb
<%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js'  %>

<!--<script src="//cdn.jsdelivr.net/highlight.js/9.5.0/highlight.min.js"></script> ##or## -->
<%#= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/highlight.min.js'  %>
<%#= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/languages/xml.min.js'  %>
<%#= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/languages/cs.min.js'  %>
<%#= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/languages/java.min.js'  %>
<%#= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/languages/javascript.min.js' %>
<%#= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/languages/ruby.min.js' %>

app/views/shared/_javascript_highlight_function.erb
<script type="text/javascript">
    $(document).ready(function () {
        //fix grow onload
        turn_textareas_autogrow();

        $(".convert-code-title ").each(function () {
            convert($(this));
        });

        $(".convert-code-options ").each(function () {
            convert($(this));
        });

        $('pre code').each(function (i, block) {
            hljs.highlightBlock(block);
        });

    });

    function convert(element) {

        var original_content = element.html().toString();

        var new_content = original_content.replace(/\[\s*\w*\s*code="xml hljs"\]/g, "<pre><code class='xml hljs'>")
                .replace(/\[\s*\w*\s*code="cs hljs"\]/g, "<pre><code class='cs hljs'>")
                .replace(/\[\s*\w*\s*code="css hljs"\]/g, "<pre><code class='css hljs'>")
                .replace(/\[\s*\w*\s*code="javascript"\]/g, "<pre><code class='javascript'>")
                .replace(/\[\/code\]/g, "</code></pre>");

        element.html(new_content);
    }


    function turn_textareas_autogrow() {

        $('textarea.autogrow').each(function () {//fix grow onload
            autogrower($(this));
        });

        $('textarea.autogrow').bind('input keyup change cut paste', function () {
            autogrower($(this));
        });
    }

    function autogrower(element) {
        $(element).css("height", 'auto');
        $(element).css("height", element[0].scrollHeight + 3 + 'px');
    }


</script>

app/views/shared/_logo.html.erb
<div class="logo">
  Exam Certification
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default" style="border-radius: 0" role="navigation">
  <div class="">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Exam Certification', surveys_path, class: "navbar-brand" %>
      <%#= link_to image_tag('logo_sh30.png'), dashboard_path, class: "navbar-brand" %>
      <%#= render 'shared/logo' %>
    </div>

    <div class="nav navbar-nav navbar-right" style="margin-right: 70px; margin-top: 10px; ">
      <% if user_signed_in? %>
          <span class="glyphicon glyphicon-user navbar-link" aria-hidden="true"></span>
          <span class="navbar-link"><%= t('welcome') %> <%= current_user.name.blank? ? current_user.email : current_user.name %></span>
          <%= link_to('', destroy_user_session_path, method: :delete, data: {confirm: t('confirm_logout'), ok: t('ok'), cancel: t('cancel')},title: 'Logout', class: 'glyphicon glyphicon-log-out btn btn-sm btn-default') %>
      <% end %>
    </div>


  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li class="<%#= is_active?(surveys_path) %>">
        <%#= link_to surveys_path do %>
            <!--All surveys-->
            <!--<span class='badge'> <%#= surveys_count %> </span>-->
        <%# end -%>
      </li>
    </ul>
  </div>
</div>
</div>





<!--<header>-->
<!--<div class="navbar navbar-default navbar-static-top" role="navigation">-->
<!--<div class="container">-->
<!--<div class="navbar-header">-->
<!--<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">-->
<!--<span class="sr-only">Toggle navigation</span>-->
<!--<span class="icon-bar"></span>-->
<!--<span class="icon-bar"></span>-->
<!--<span class="icon-bar"></span>-->
<!--</button>-->
<!--<%#= link_to surveys_path, class: 'navbar-brand' do %>-->
<!--<%#= render 'shared/logo' %>-->
<!--<%# end -%>-->
<!--</div>-->
<!--<div class="navbar-collapse collapse">-->
<!--<ul class="nav navbar-nav">-->
<!--<li class="<%#= is_active?(surveys_path) %>">-->
<!--<%#= link_to surveys_path do %>-->
<!--All surveys-->
<!--<span class='badge'> <%#= surveys_count %> </span>-->
<!--<%# end -%>-->
<!--</li>-->
<!--</ul> -->
<!--</div>-->
<!--</div>-->
<!--</div>-->
<!--</header>-->

app/views/shared/_stylesheet_cdn_includes.erb
<%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'  %>
<%#= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/styles/railscasts.min.css' %>

<!--<link rel="stylesheet" href="//cdn.jsdelivr.net/highlight.js/9.5.0/styles/default.min.css">-->